
CMAKE_POLICY(SET CMP0011 NEW)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")

MESSAGE(STATUS "Current module path: ${CMAKE_MODULE_PATH}")

FIND_PACKAGE(NVSHMEM REQUIRED)

KOKKOS_TPL_OPTION(NVSHMEM On)
KOKKOS_TPL_OPTION(MPI On)

KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME NVSHMEM NVSHMEM)
KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME MPI::MPI_CXX MPI)

install(FILES ${CMAKE_CURRENT_LIST_DIR}/Modules/FindNVSHMEM.cmake
        DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/Modules )
