
CMAKE_POLICY(SET CMP0011 NEW)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/Modules")

IF( KOKKOS_ENABLE_NVSHMEMSPACE)
   SET(KOKKOS_MPI_REQUIRED ON)

   FIND_PACKAGE(NVSHMEM REQUIRED)

   KOKKOS_TPL_OPTION(NVSHMEM On)
   KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME NVSHMEM::NVSHMEM NVSHMEM)

   KOKKOS_TPL_OPTION(OSHMEM On)
   KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME NVSHMEM::OSHMEM OSHMEM)
ENDIF()
IF( KOKKOS_ENABLE_MPISPACE)
   FIND_PACKAGE(MPI)
   SET(KOKKOS_MPI_REQUIRED ON)
ENDIF()

IF ( KOKKOS_MPI_REQUIRED )
   KOKKOS_TPL_OPTION(MPI On)
   KOKKOS_LINK_TPL(kokkoscore PUBLIC IMPORTED_NAME MPI::MPI_CXX MPI)
ENDIF()

install(FILES ${CMAKE_CURRENT_LIST_DIR}/Modules/FindNVSHMEM.cmake
        DESTINATION ${CMAKE_INSTALL_PREFIX}/cmake/Modules )
